export type CardProps = {
    id?: string | undefined,
    automationId?: string,
    width?: string | undefined,
    height?: string | undefined,
    flex?: string | undefined,
    padding?: string | undefined,
    margin?: string | undefined,
    minWidth?: string | undefined,
    maxHeight?: string | undefined,
    maxWidth?: string | undefined,
    minHeight?: string | undefined,
    isEnabled?: any | undefined,
    onClick?: (event: React.MouseEvent<HTMLDivElement>) => void,
    ref?: () => string | undefined,
    backgroundColor?: string | undefined,
    display?: string | undefined,
    focusBoxShadow?: string | undefined,
    borderRadius?: string | undefined,
    focusColor?: string | undefined,
    activeBoxShadow?: string | undefined,
    justifyContent?: string | undefined,
    containerHeight?: string | undefined,
    containerWidth?: string | undefined,
    boxShadow?: string | undefined,
    flexDirection?: string | undefined,
    alignItems?: string | undefined,
    overflow?: string | undefined,
    hoverBorder?: string | undefined,
    hoverBoxShadow?: string | undefined,
    hoverColor?: string | undefined,
    focusBorder?: string | undefined,
    activeOpacity?: string | undefined,
    children?:any | undefined,
    color?:string | undefined,
    border?:string | undefined,
    cardDisplay?: string | undefined,
    backgroundImageUrl?: string | undefined,
    boxSizing?: string | undefined,
    iconUrl?: string | undefined,
    iconWidth?: string | undefined,
    iconHeight?: string | undefined,
    headingAlign?: string | undefined,
    headingSize?:any | undefined,
    headingWeight?:string | undefined,
    heading?:string | undefined,
    bodyAlign?: string | undefined,
    bodySize?: string | undefined,
    body?: string | undefined,
    textAlign?: string | undefined,
    cardMargin?: string | undefined,
    cardPadding?:any | undefined,
    flexGrow?:string | undefined,
    cardWidth?:string | undefined,
    subtitleMargin?: string | undefined,
    titleMargin?: string | undefined,
    titleWeight?: string | undefined,
    titleSize?: string | undefined,
    textMargin?: string | undefined
    buttonAutomationId?: string | undefined,
    activeBackgroundColor?: string | undefined,
    activeColor?: string | undefined,
    activeBorderColor?: string | undefined,
    buttonHeight?: string | undefined,
    buttonMinWidth?:any | undefined,
    buttonMargin?:string | undefined,
    buttonBorder?:string | undefined,
    buttonActiveOpacity?: string | undefined,
    buttonFontSize?: string | undefined,
    buttonFontWeight?: string | undefined,
    buttonFontFamily?: string | undefined,
    buttonText?: string | undefined
    buttonId?: string | undefined,
    text?: string | undefined,
    isTextHTML?: string | undefined,
    __html?: any | undefined,
    title?: string | undefined,
    subtitle?:any | undefined,
    imageObjectFit?:string | undefined,
    imageHeight?:string | undefined,
    imageWidth?: string | undefined,
    image?: string | undefined,
    alt?: any | undefined,
    showSeperator?: boolean,
    onSecondaryClick?: string,
    secondaryText?:string,
    onPrimaryClick?:string,
    primaryText?:string
}