export type CloseButtonProps = {
    display: string,
    width: string ,
    height: string,
    minHeight: string,
    minWidth: string,
    maxHeight:string,
    maxWidth: string,
    flex: string,
    flexWrap: string,
    alignItems: string,
    padding: string,
    margin: string,
    backgroundImage: string,
    backgroundColor: string,
    hoverBackgroundColor:string,
    cursor: string,
    border:string,
    borderRadius: string,
    onClick?: (event: React.MouseEvent<HTMLDivElement>) => void,
    history: { goBack: () => any }
    imageHeight: string,
    imageWidth: string,
    objectFit:string,
    src: string,
}