export type BaseProps = {
    display?: string,
    width?: string,
    height?: string,
    minHeight?: string,
    minWidth?: string,
    maxHeight?: string,
    maxWidth?: string,
    flex?: string ,
    flexWrap?: string ,
    flexDirection?: string,
    padding?: string  ,
    margin?: string,
    backgroundImage?: string ,
    backgroundColor?: string ,
    background?:string ,
    color?: string ,
    border?:string ,
    borderRadius?: string,
    overflow?: string,
    boxShadow?:string,
    justifyContent?: string,
    alignItems?: string,
    alignContent?: string,
    cursor?: string,
    transition?: string,
    transform?: string,
    hoverWidth?: string,
    hoverHeight?: string,
    hoverFlex?: string,
    hoverFlexDirection?: string,
    hoverPadding?: string,
    hoverMargin?: string,
    hoverBackgroundImage?: string,
    hoverBackgroundColor?: string,
    hoverBackground?: string,
    hoverColor?: string,
    hoverBorder?: string,
    hoverBorderRadius?: string,
    hoverOverflow?: string,
    hoverBoxShadow?: string,
    hoverJustifyContent?: string,
    hoverAlignItems?: string,
    hoverCursor?: string,
    hoverTransform?: string ,
    outline?: string ,
    position?: string ,
    opacity?: string ,
    top?: string ,
    bottom?: string ,
    left?: string ,
    right?: string ,
    borderTop?: string ,
    borderBottom?: string ,
    borderLeft?: string,
    borderRight?: string,
    visibility?: string,
    zIndex?: string,
    boxSizing?: string,
    float?: string,
    verticalAlign?: string,
    alignmentBaseline?: string,
    onClick?: () => any; 
    history?: { goBack: () => any } ,
}