const assetBaseUri = 'https://static.vodacomdigitalassets.co.za/common/'

export const FormFactorTypes = {
  Default: 'Default',
  Desktop: 'Desktop',
  Mobi: 'Mobi',
  Tablet: 'Tablet',
  Feature: 'Feature',
};

export const FontFamilies = {
  VodafoneLightEot: `${assetBaseUri}fonts/vodafone-light.eot`,
  VodafoneLightEotIeFix: `${assetBaseUri}fonts/vodafone-light.eot?#ie-fix`,
  VodafoneLightWoff: `${assetBaseUri}fonts/vodafone-light.woff`,
  VodafoneRegularEot: `${assetBaseUri}fonts/vodafone-regular.eot`,
  VodafoneRegularEotIeFix: `${assetBaseUri}fonts/vodafone-regular.eot?#ie-fix`,
  VodafoneRegularWoff: `${assetBaseUri}fonts/vodafone-regular.woff`,
  VodafoneBoldEot: `${assetBaseUri}fonts/vodafone-bold.eot`,
  VodafoneBoldEotIeFix: `${assetBaseUri}fonts/vodafone-bold.eot?#ie-fix`,
  VodafoneBoldWoff: `${assetBaseUri}fonts/vodafone-bold.woff`,
  VodafoneExtraBoldEot: `${assetBaseUri}fonts/vodafone-extra-bold.eot`,
  VodafoneExtraBoldEotIeFix: `${assetBaseUri}fonts/vodafone-extra-bold.eot?#ie-fix`,
  VodafoneExtraBoldWoff: `${assetBaseUri}fonts/vodafone-extra-bold.woff`,
}

export const ColorCodes = {
  CurrentColor: 'currentColor',
  Transparent: 'rgba(0,0,0,0)',
  Black: '#000000',
  Grey1: '#F9F9F9',
  Grey2: '#F4F4F4',
  Grey3: '#EBEBEB',
  Grey4: '#DBDBDB',
  Grey5: '#CCCCCC',
  Grey6: '#999999',
  Grey7: '#666666',
  Grey8: '#4A4D4E',
  Grey9: '#333333',
  Grey10: '#25282B',
  Grey11: '#282828',
  Grey12: '#4A4A4A',
  Grey13: '#F1F1F1',
  Grey14: '#E5E5E5',
  Grey15: '#E8E8E8',
  White: '#FFFFFF',
  Red1: '#E60000',
  Red2: '#BD0000',
  Red3: '#BE0006',
  Red4: '#820000',
  RedDigital: '#FF0000', // Deprecated... probably.
  Blue1: '#00B0CA',
  Blue2: '#007C92',
  Blue3: '#005765',
  Blue4: '#4FAFC7',
  Blue5: '#96CCD4',
  Purple1: '#9C2AA0',
  Purple2: '#5E2750',
  Yellow1: '#FEC800',
  Yellow2: '#EB9700',
  Green1: '#A8B400',
  Green2: '#387C00',
  Green3: '#769C50',
  Green4: '#528324',
  Green5: '#428600',
  Green6: '#2FB650',
}


export const Images = {

  Backgrounds: {
    Banner: `${assetBaseUri}images/backgrounds/banner.svg`,
  },

  Icons: {
    ArrowOutline: `${assetBaseUri}images/icons/arrow.svg`,
    PlusCircle: `${assetBaseUri}images/icons/add.svg`,
    Plus: `${assetBaseUri}images/icons/add-or-plus.svg`,
    Bill: `${assetBaseUri}images/icons/bill-hi-dark.svg`,
    Phone: `${assetBaseUri}images/icons/call-hi-dark.svg`,
    CartOutline: `${assetBaseUri}images/icons/cart-outline.svg`,
    Documents: `${assetBaseUri}images/icons/case-study-hi-dark.svg`,
    HeartHand: `${assetBaseUri}images/icons/charity_giving.svg`,
    Camera: `${assetBaseUri}images/icons/camera.svg`,
    CheckOutline: `${assetBaseUri}images/icons/check-outline.svg`,
    CheckMark: `${assetBaseUri}images/icons/checkmark.svg`,
    CheckMarkCircle: `${assetBaseUri}images/icons/checkmark-circle.svg`,
    Chevron: `${assetBaseUri}images/icons/chevron.svg`,
    Close: `${assetBaseUri}images/icons/close.svg`,
    CloseWhite: `${assetBaseUri}images/icons/close-white.svg`,
    CloseCircle: `${assetBaseUri}images/icons/extras-and-services-hi.svg`,
    CloudArrow: `${assetBaseUri}images/icons/cloud.svg`,
    CreditCard: `${assetBaseUri}images/icons/card-outline.svg`,
    Desktop: `${assetBaseUri}images/icons/desktop-hi-dark.svg`,
    Drivers: `${assetBaseUri}images/icons/drivers.svg`,
    DesktopOutline: `${assetBaseUri}images/icons/desktop-outline.svg`,
    Leaf: `${assetBaseUri}images/icons/environment.svg`,
    Error: `${assetBaseUri}images/icons/warning-hi-dark.svg`,
    ErrorOutline: `${assetBaseUri}images/icons/error.svg`,
    ErrorCircle: `${assetBaseUri}images/icons/icon-warning.svg`,
    Hamburger: `${assetBaseUri}images/icons/hamburger.svg`,
    Home: `${assetBaseUri}images/icons/home-hi-dark.svg`,
    HomeOutline: `${assetBaseUri}images/icons/home.svg`,
    InfoCircle: `${assetBaseUri}images/icons/icon-info.svg`,
    PhoneOutline: `${assetBaseUri}images/icons/landline-or-call.svg`,
    ProfileOutline: `${assetBaseUri}images/icons/profile-outline.svg`,
    ProfileBusiness: `${assetBaseUri}images/icons/business-profile-hi-dark.svg`,
    ThumbsUpOutline: `${assetBaseUri}images/icons/like.svg`,
    Logo: `${assetBaseUri}images/icons/logo.svg`,
    LogoOutline: `${assetBaseUri}images/icons/logo-outline.svg`,
    LogoReverse: `${assetBaseUri}images/icons/logo-reverse.svg`,
    LogoutOutline: `${assetBaseUri}images/icons/logout-outline.svg`,
    Mail: `${assetBaseUri}images/icons/mail-read-hi.svg`,
    MailOutline: `${assetBaseUri}images/icons/mail.svg`,
    Mobile: `${assetBaseUri}images/icons/mobile-hi-dark.svg`,
    MobileOutline: `${assetBaseUri}images/icons/mobile-outline.svg`,
    MobileLogo: `${assetBaseUri}images/icons/mobile-hi-dark-2.svg`,
    MyVodafone: `${assetBaseUri}images/icons/my-vodafone-hi-dark.svg`,
    MobilePlusOutline: `${assetBaseUri}images/icons/new-contract.svg`,
    Passport: `${assetBaseUri}images/icons/passport.svg`,
    Payment: `${assetBaseUri}images/icons/payment-hi-dark.svg`,
    PadLock: `${assetBaseUri}images/icons/padlock-outline.svg`,
    Refresh: `${assetBaseUri}images/icons/refresh.svg`,
    SAID: `${assetBaseUri}images/icons/sa_id.svg`,
    ScreenOutline: `${assetBaseUri}images/icons/screen-outline.svg`,
    ShieldCheckOutline: `${assetBaseUri}images/icons/shield-check-outline.svg`,
    ShieldPlusOutline: `${assetBaseUri}images/icons/shield-plus-outline.svg`,
    SimCard: `${assetBaseUri}images/icons/simcard-outline.svg`,
    SimSwap: `${assetBaseUri}images/icons/sim-swap.svg`,
    SmartId: `${assetBaseUri}images/icons/smart-id.svg`,
    SpeechBubbleOutline: `${assetBaseUri}images/icons/speech-bubbles-outline.svg`,
    SpeechMark: `${assetBaseUri}images/icons/speech-mark-cut.svg`,
    Star: `${assetBaseUri}images/icons/star.svg`,
    StarOutline: `${assetBaseUri}images/icons/star-outlined.svg`,
    SuccessCircle: `${assetBaseUri}images/icons/icon-success.svg`,
    User: `${assetBaseUri}images/icons/icon-user.svg`,
    QuestionMarkCircle: `${assetBaseUri}images/icons/support-hi-dark.svg`,
    QuestionMarkGreyCircle: `${assetBaseUri}images/icons/question-mark-grey.svg`,
    Sync: `${assetBaseUri}images/icons/vc-sync.svg`,
    Text: `${assetBaseUri}images/icons/text-hi.svg`,
    TrashCanOutline: `${assetBaseUri}images/icons/trashcan-outline.svg`,
    UpDownArrowOutline: `${assetBaseUri}images/icons/updown-arrows-outline.svg`,
    MobileArrowOutline: `${assetBaseUri}images/icons/upgrade.svg`,
    Warning: `${assetBaseUri}images/icons/tutorials-hi-dark-orange.svg`,
    WarningCircle: `${assetBaseUri}images/icons/icon-warning.svg`,
    WarningBlack: `${assetBaseUri}images/icons/warning.svg`,
    Search: `${assetBaseUri}images/icons/search.svg`,
    J4U: `${assetBaseUri}images/icons/j4u.svg`,
    OpenedBox: `${assetBaseUri}images/icons/bundles-hi-dark.svg`,
    Tooltip: `${assetBaseUri}images/icons/tooltip.svg`,
    Bell: `${assetBaseUri}images/icons/bell.svg`,
    Info: `${assetBaseUri}images/icons/info.svg`,
    BackArrow: `${assetBaseUri}images/icons/back-arrow.svg`,
    More: `${assetBaseUri}images/icons/vertical-more.svg`
  },

  AppStore: `${assetBaseUri}images/app-store.svg`,
  PlayStore: `${assetBaseUri}images/play-store.svg`,
};


export const FontSizes = {
  Smallest: '14px',
  Smaller: '16px',
  Small: '18px',
  Normal: '20px',
  Big: '24px',
  Bigger: '28px',
  Biggest: '50px',
};