import {
    ColorCodes
  } from 'common/constants';
  
  export const Themes = {
    PreLogin: {
      Background: {
        Primary1: ColorCodes.White,
        Primary2: ColorCodes.Grey1,
        Primary3: ColorCodes.Grey2,
        Secondary1: ColorCodes.Grey3,
        Secondary2: ColorCodes.Grey8,
        Secondary3: ColorCodes.Grey9,
        Secondary4: ColorCodes.Grey10,
        Accent1: ColorCodes.Blue3,
        Accent2: ColorCodes.Purple2,
      },
      Text: {
        Primary1: ColorCodes.Grey9,
        Primary2: ColorCodes.Grey8,
        Secondary1: ColorCodes.White,
        Secondary2: ColorCodes.Grey6,
        Secondary3: ColorCodes.Grey7,
        Secondary4: ColorCodes.Black,
        Accent1: ColorCodes.Blue1,
        Accent2: ColorCodes.Blue2,
        Accent3: ColorCodes.Blue3,
        Accent4: ColorCodes.Green2,
        Accent5: ColorCodes.Green1,
        Accent6: ColorCodes.Purple1,
        Error1: ColorCodes.Red2,
      },
      Line: {
        Primary1: ColorCodes.Grey4,
        Primary2: ColorCodes.Grey3,
        Secondary1: ColorCodes.Grey2,
        Secondary2: ColorCodes.Grey5,
        Secondary3: ColorCodes.Grey9,
        Secondary4: ColorCodes.Grey8,
        Accent1: ColorCodes.Blue1,
        Accent2: ColorCodes.Blue2,
        Accent3: ColorCodes.Blue3,
        Accent4: ColorCodes.Green2,
        Error1: ColorCodes.Red1,
      },
      Shape: {
        Primary1: ColorCodes.White,
        Primary2: ColorCodes.Grey2,
        Primary3: ColorCodes.Grey9,
        Secondary1: ColorCodes.Grey2,
        Secondary2: ColorCodes.Grey5,
        Secondary3: ColorCodes.Grey9,
        Secondary4: ColorCodes.Grey8,
        Accent1: ColorCodes.Blue1,
        Accent2: ColorCodes.Blue2,
        Accent3: ColorCodes.Blue3,
        Accent4: ColorCodes.Green2,
        Accent5: ColorCodes.Green1,
        Accent6: ColorCodes.Purple1,
        Accent7: ColorCodes.Purple2,
        Accent8: ColorCodes.Yellow1,
        Accent9: ColorCodes.Yellow2,
        Error1: ColorCodes.Red1,
        Error2: ColorCodes.Red2,
        Error3: ColorCodes.Red3,
      },
    },
    PostLogin: {
      Background: {
        Primary1: ColorCodes.White,
        Primary2: ColorCodes.Grey1,
        Primary3: ColorCodes.Grey2,
        Secondary1: ColorCodes.Grey3,
        Secondary2: ColorCodes.Grey8,
        Secondary3: ColorCodes.Grey9,
        Secondary4: ColorCodes.Grey10,
        Accent1: ColorCodes.Red2,
        Accent2: ColorCodes.Red3,
      },
      Text: {
        Primary1: ColorCodes.Grey9,
        Primary2: ColorCodes.Grey8,
        Secondary1: ColorCodes.White,
        Secondary2: ColorCodes.Grey6,
        Secondary3: ColorCodes.Grey7,
        Secondary4: ColorCodes.Black,
        Accent1: ColorCodes.Red1,
        Accent2: ColorCodes.Red2,
        Accent3: ColorCodes.Red3,
        Accent4: ColorCodes.Purple1,
        Accent5: ColorCodes.Purple2,
        Accent6: ColorCodes.Green1,
        Error1: ColorCodes.Red2,
      },
      Line: {
        Primary1: ColorCodes.Grey4,
        Primary2: ColorCodes.Grey3,
        Secondary1: ColorCodes.Grey2,
        Secondary2: ColorCodes.Grey5,
        Secondary3: ColorCodes.Grey9,
        Secondary4: ColorCodes.Grey8,
        Accent1: ColorCodes.Red1,
        Accent2: ColorCodes.Red2,
        Accent3: ColorCodes.Red3,
        Accent4: ColorCodes.Purple1,
        Error1: ColorCodes.Red1,
      },
      Shape: {
        Primary1: ColorCodes.White,
        Primary2: ColorCodes.Grey2,
        Primary3: ColorCodes.Grey9,
        Secondary1: ColorCodes.Grey2,
        Secondary2: ColorCodes.Grey5,
        Secondary3: ColorCodes.Grey9,
        Secondary4: ColorCodes.Grey8,
        Accent1: ColorCodes.Red1,
        Accent2: ColorCodes.Red2,
        Accent3: ColorCodes.Red3,
        Accent4: ColorCodes.Purple1,
        Accent5: ColorCodes.Purple2,
        Accent6: ColorCodes.Green1,
        Accent7: ColorCodes.Blue2,
        Accent8: ColorCodes.Yellow1,
        Accent9: ColorCodes.Yellow2,
        Error1: ColorCodes.Red1,
        Error2: ColorCodes.Red2,
        Error3: ColorCodes.Red3,
      },
    },
  }