export type TextProps = {
    display?: string,
    fontFamily?: string,
    fontSize?: string,
    fontWeight?: string,
    fontStyle?: string,
    lineHeight?: string,
    letterSpacing?: string,
    padding?: string,
    margin?: string,
    textAlign?: string,
    transform?: string,
    textDecoration?: string,
    position?: string,
    flex?: string,
    top?: string,
    justifyContent?: string,
    bottom?: string,
    alignSelf?: string,
    left?: string,
    right?: string,
    whiteSpace?: string,
    textOverflow?: string,
    overflow?: string,
    width?: string,
    hyphens?: string,
    wordBreak?: string,
    wordWrap?: string,
    text?: string,
    
}