import { string } from "prop-types"

export type NotificationProps = {
    id?: any | undefined,
    automationId?: string | undefined,
    backgroundColor?: string | undefined,
    imageUrl?: string | undefined,
    width?: string | undefined,
    flex?: string | undefined,
    margin?: string | undefined,
    minHeight?: string | undefined,
    minWidth?: string | undefined,
    maxHeight?: string | undefined,
    maxWidth?: string | undefined,
    padding?: string | undefined,
    height?: string | undefined,
    color?: string | undefined,
    fontSize?: string | undefined,
    onCloseClick?: (event: React.MouseEvent<HTMLDivElement>) => void,
    closeImageUrl?: string | undefined,
    closeText?: string | undefined,
    src?: any ,
    position?: string | undefined,
    left?: string | undefined,
    top?: string | undefined,
    right?: string | undefined,
    bottom?: string | undefined,
    align?: string | undefined,
    snackbarPadding?: string | undefined,
    heading?: string| undefined,
    key?: string | undefined,
    text?:string | undefined,
    onClick?: (event: React.MouseEvent<HTMLDivElement> ) => void,
    textLine?: React.ReactNode

}