import { string } from "prop-types"

export type NotificationProps = {
    id?: any,
    automationId?: string,
    backgroundColor?: string,
    imageUrl?: string,
    width?: string,
    flex?: string,
    margin?: string,
    minHeight?: string,
    minWidth?: string,
    maxHeight?: string,
    maxWidth?: string,
    padding?: string,
    height?: string,
    color?: string,
    fontSize?: string,
    onCloseClick?: (event: React.MouseEvent<HTMLDivElement>) => void,
    closeImageUrl?: string,
    closeText?: string,
    src?: string ,
    position?: string,
    left?: string,
    top?: string,
    right?: string,
    bottom?: string,
    align?: string,
    snackbarPadding?: string,
    heading?: string| undefined,
    key?: string,
    text?:string,
    onClick?: (event: React.MouseEvent<HTMLDivElement> ) => void,
    textLine?: React.ReactNode

}